spring:
  datasource:
    url: jdbc:mysql://192.168.1.172:3306/icharge?useUnicode=true&characterEncoding=UTF-8
    username: icharge
    password: icharge
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      stat-view-servlet:
        allow: true
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
  redis:
    host: 192.168.1.101 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
server:
  port: 8080
