spring:
  datasource:
    url: jdbc:mysql://192.168.1.172:3306/icharge?useUnicode=true&characterEncoding=UTF-8
    username: icharge
    password: icharge
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      stat-view-servlet:
        allow: true
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
server:
  port: 8080
